### ISSUE TITLE
exception str() failed on eol

### ISSUE THREAD

**Issue by bew** [LionelAuroux/pyrser#14]
Hi,
On a first try implementing a CSV parser, I get a `exception str() failed` with no other infos, when using the default rule `eol`

Input :

``` csv
A;B;C;D
E;F;G
```

Parser : 

``` python
class parserCSV(grammar.Grammar):
    entry = "Csv"
    grammar = """
        Csv = [
            @ignore("null")
            Lines
            eof
        ]

        Lines = [
            Line* LastLine
        ]

        Line = [ Fields eol ]
        LastLine = [ Fields eol? ]

        Fields = [ id [ ';' id ]* ]
    """
```

Full error : 

```
Traceback (most recent call last):
  File "./test.py", line 8, in <module>
    res = csv.parse_file(sys.argv[1])
  File "/usr/lib/python3.5/site-packages/pyrser/grammar.py", line 165, in parse_file
    return self._do_parse(entry)
  File "/usr/lib/python3.5/site-packages/pyrser/grammar.py", line 130, in _do_parse
    raise self.diagnostic
pyrser.error.Diagnostic: <exception str() failed>
```

When I change `Line` & `LastLine` to : 

```
        Line = [ Fields end ]
        LastLine = [ Fields end? ]

        end = [ "::" ]
```

With input : 

```
A;B;C;D::E;F;G
```

It works correctly, so the error should be somewhere aroud `eol`

And finally, when I change `end` to `eol` or to `'\r'? '\n'` it still raise an exception...

Good luck !

**Comment by LionelAuroux** [comment]
Grammar false and can't reproduce error... close
