### ISSUE TITLE
built-in hooks like #set(dst, src) not working

### ISSUE THREAD

**Issue by deb0ch** [LionelAuroux/pyrser#3]
Salut !

@LionelAuroux : Avec la version de Pyrser qui m'est venue avec `pip3 install pyrser` mardi 15 septembre 2015 j'ai eu un bug avec #set(dst, src) que je t'avais montré et que tu n'avais pas compris sur le moment. Du coup voici l'issue que tu m'avais demandé de rédiger.

A noter que je n'ai testé le bug qu'avec #set(dst, src), je n'ai essayé avec aucun autre built-in.

(Et on avait aussi essayé avec d'autres manières de spécifier l'import que tu m'avais dit d'essayer sur le moment mais qui n'avaient pas marché non plus.)

```
from pyrser import grammar, meta
from pyrser.hooks import *

class parserExample(grammar.Grammar):
    entry = "Example"
    grammar = """ 
    Example = [ id:i eof #set(_, i) ]

    """

Ex = parserExample()
res = Ex.parse("someExample")
```

outputs:

```
Traceback (most recent call last):
  File "parserCSV.py", line 12, in <module>
    res = Ex.parse("someExample")
  File "/usr/local/lib/python3.4/dist-packages/pyrser/grammar.py", line 144, in parse
    return self._do_parse(entry)
  File "/usr/local/lib/python3.4/dist-packages/pyrser/grammar.py", line 124, in _do_parse
    raise self.diagnostic
  File "/usr/local/lib/python3.4/dist-packages/pyrser/grammar.py", line 107, in _do_parse
    res = self.eval_rule(entry)
  File "/usr/local/lib/python3.4/dist-packages/pyrser/parsing/base.py", line 215, in eval_rule
    res = rule_to_eval(self)
  File "/usr/local/lib/python3.4/dist-packages/pyrser/parsing/functors.py", line 29, in __call__
    res = self.do_call(parser)
  File "/usr/local/lib/python3.4/dist-packages/pyrser/parsing/functors.py", line 165, in do_call
    if not pt(parser):
  File "/usr/local/lib/python3.4/dist-packages/pyrser/parsing/functors.py", line 29, in __call__
    res = self.do_call(parser)
  File "/usr/local/lib/python3.4/dist-packages/pyrser/parsing/functors.py", line 502, in do_call
    return parser.eval_hook(self.name, valueparam)
  File "/usr/local/lib/python3.4/dist-packages/pyrser/parsing/base.py", line 229, in eval_hook
    raise self.diagnostic
pyrser.error.Diagnostic: ===============================================================================
error : Unknown hook : set
from /tmp/tmpt4kdv4hy at line:1 col:12 :
someExample
           ^
-------------------------------------------------------------------------------
error : Exception during the evaluation of 'eof'
from /tmp/tmpt4kdv4hy at line:1 col:12 :
someExample
           ^
-------------------------------------------------------------------------------
error : Parse error in 'eof'
from /tmp/tmpt4kdv4hy at line:1 col:12 :
someExample
           ^
-------------------------------------------------------------------------------
```

**Comment by LionelAuroux** [comment]
corrected

**Comment by deb0ch** [comment]
Nice ! :thumbsup::sparkles:

Au plaisir de te recroiser à Tek :D
